### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by patelkrushi29**

### CODE REVIEW

**Review by LukeMizuhashi — APPROVED** [review]
Whoa, cool! I'd never actually seen the **= operator before! Neat find. :)

**Comment by patelkrushi29** [comment]
oh eah thanks I know good amount of python but not much javascript and java
so that could be wrong.

**Comment by LukeMizuhashi** [comment]
It's probably right. Later, we'll cover how to write unit tests ( and use those to prove whether it's right or not ).

**Comment by LukeMizuhashi** [comment]
Lol. I just noticed this commit was on the Python scripts--not the JavaScript.

Today I Learned : **= is a valid operator in Python and JavaScript!

**Comment by patelkrushi29** [comment]
Hahah yeha I knew it was a thing in python so I tried in Javascript and it
looked like it could work bt I haven't checked yet

**Comment by patelkrushi29** [comment]
I will do the Java one tomorrow most likely

**Pull request merged**
