### PR TITLE
Update constructor.js

### PR DESCRIPTION
**Pull request by patelkrushi29**

### CODE REVIEW

**Review by LukeMizuhashi — CHANGES_REQUESTED** [review]
Looks like subtract and power got some copy-pasta.

**Comment by patelkrushi29** [comment]
What you mean?

**Comment by LukeMizuhashi** [comment]
Oh, sorry. I originally reviewed this pull request on my phone; the display on the mobile website made it look like subtract had been implemented using copy-pasted code from a different function.

But--now that I'm on my laptop--I can see that subtract is correct.

power isn't quite right. But, I also didn't write a contract indicating what power should do. So--it's fair.

Good enough for now.

Let's move on to learning how to use these objects in programs and unit testing them. :)

**Comment by patelkrushi29** [comment]
Oh yeah sounds like a plan. I also know how to use git shell now so that's
helpful too lol

**Pull request merged**
